version: '3.8'

services:
  backend:
    build:
      context: ./backend/StudentAttendanceApi
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/student-attendance-frontend
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
